version: '3.8'

services:
  postgres-test:
    image: postgres:15.3
    container_name: otboo-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: otboo-db
      POSTGRES_USER: otboo-user
      POSTGRES_PASSWORD: otboo-password
    ports:
      - "5434:5432"
    networks:
      - otboo-test-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "otboo-user" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-test:
    image: redis:7.2
    container_name: otboo-redis-test
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - otboo-test-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  otboo-test-net:
    driver: bridge
