spring:
  application:
    name: otboo

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  batch:
    jdbc:
      initialize-schema: NEVER

api:
  kma:
    base-url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
    service-key: "${API_KMA_SERVICE_KEY}"

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG

jwt:
  secret: MySuperSecretJwtKeyThatShouldBeLongEnough123
  expiration: 600000 # 10? (??? ??)
  refresh-token-validity-in-ms: 604800000
