spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  batch:
    jdbc:
      initialize-schema: NEVER

api:
  kma:
    base-url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
    service-key: "${API_KMA_SERVICE_KEY}"
  kakao:
    rest-key: "${API_KAKAO_REST_KEY}"
